version: '3.4'

services:
  message-broker:
    image: rabbitmq:management-alpine
    container_name: MessageBroker
    hostname: message-broker
    environment:
         RABBITMQ_DEFAULT_USER: guest
         RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672
    networks: 
        - proxybackend
 
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: APIGateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
        - 5000:8080
        - 5001:8081
    networks: 
        - proxybackend

  financial:
    image: ${DOCKER_REGISTRY-}financial
    build:
      context: .
      dockerfile: Financial/Dockerfile
    ports:
        - 4080:8080
        - 4081:8081
    networks: 
        - proxybackend
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=amqp://message-broker:5672
        - RabbitMQ__Username=guest
        - RabbitMQ__Password=guest

  financialdatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: FinancialDatabase
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    networks: 
        - proxybackend
    ports:
      - "1333:1433"

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
        - 5080:8080
        - 5081:8081
    networks: 
        - proxybackend
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=amqp://message-broker:5672
        - RabbitMQ__Username=guest
        - RabbitMQ__Password=guest

  identitydatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: IdentityDatabase
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1533:1433"
    networks: 
        - proxybackend

  infrastructures:
    image: ${DOCKER_REGISTRY-}infrastructures
    build:
      context: .
      dockerfile: Infrastructures/Dockerfile
    ports:
        - 6080:8080
        - 6081:8081
    networks: 
        - proxybackend
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=amqp://message-broker:5672
        - RabbitMQ__Username=guest
        - RabbitMQ__Password=guest

  infrastructuresdatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: InfrastructuresDatabase
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1633:1433"
    networks: 
        - proxybackend

  membersteams:
    image: ${DOCKER_REGISTRY-}membersteams
    build:
      context: .
      dockerfile: MembersTeams/Dockerfile
    ports:
        - 7080:8080
        - 7081:8081
    networks: 
        - proxybackend
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=amqp://message-broker:5672
        - RabbitMQ__Username=guest
        - RabbitMQ__Password=guest

  membersteamsdatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MembersTeamsDatabase
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1733:1433"
    networks: 
        - proxybackend

  trainingcompetition:
    image: ${DOCKER_REGISTRY-}trainingcompetition
    build:
      context: .
      dockerfile: TrainingCompetition/Dockerfile
    ports:
        - 8080:8080
        - 8081:8081
    networks: 
        - proxybackend
    environment:
        - ASPNETCORE_URLS=http://+:8080
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=amqp://message-broker:5672
        - RabbitMQ__Username=guest
        - RabbitMQ__Password=guest

  trainingcompetitiondatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: TrainingCompetitionDatabase
    environment:
      SA_PASSWORD: "P@ssw0rd2024!"
      ACCEPT_EULA: "Y"
    ports:
      - "1833:1433"
    networks: 
        - proxybackend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks: 
        - proxybackend

networks:
    proxybackend:
        name: proxybackend
        driver: bridge